/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conecbasedate;

import static conecbasedate.ConexionBD.cn;
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.DesktopManager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sun.awt.DesktopBrowse;


/**
 *
 * @author Jhan Kein
 */
public class grafico extends javax.swing.JFrame {

    /**
     * Creates new form grafico
     */
    public grafico() {
        initComponents();
        
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameUsuario = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Id_usua = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jTextContraseña = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextCorreo = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jFrameEliminar = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        JtxtELiminar = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jFrameMostar = new javax.swing.JFrame();
        jFrameModificar = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_mostrar = new javax.swing.JTable();

        jFrameUsuario.setBounds(new java.awt.Rectangle(500, 500, 650, 400));
        jFrameUsuario.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Id usuario");
        jFrameUsuario.getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 93, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Usuario");
        jFrameUsuario.getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 80, 69, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        jFrameUsuario.getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 130, 104, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nombres");
        jFrameUsuario.getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 190, 81, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Correo");
        jFrameUsuario.getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 240, 61, 22);

        Id_usua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_usuaActionPerformed(evt);
            }
        });
        jFrameUsuario.getContentPane().add(Id_usua);
        Id_usua.setBounds(210, 20, 310, 30);
        jFrameUsuario.getContentPane().add(jTextUsuario);
        jTextUsuario.setBounds(210, 70, 300, 30);
        jFrameUsuario.getContentPane().add(jTextContraseña);
        jTextContraseña.setBounds(210, 120, 300, 30);
        jFrameUsuario.getContentPane().add(jTextNombres);
        jTextNombres.setBounds(210, 180, 300, 30);
        jFrameUsuario.getContentPane().add(jTextCorreo);
        jTextCorreo.setBounds(210, 230, 300, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Ingresar Usuario");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrameUsuario.getContentPane().add(jButton6);
        jButton6.setBounds(260, 310, 200, 50);

        jFrameEliminar.setBounds(new java.awt.Rectangle(450, 450, 450, 450));
        jFrameEliminar.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Id de Usuario");
        jFrameEliminar.getContentPane().add(jLabel6);
        jLabel6.setBounds(126, 48, 134, 26);
        jFrameEliminar.getContentPane().add(JtxtELiminar);
        JtxtELiminar.setBounds(81, 104, 241, 40);

        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jFrameEliminar.getContentPane().add(jButton7);
        jButton7.setBounds(149, 188, 106, 39);

        jFrameMostar.setBounds(new java.awt.Rectangle(500, 500, 500, 500));
        jFrameMostar.getContentPane().setLayout(null);

        jFrameModificar.setBounds(new java.awt.Rectangle(500, 500, 500, 500));
        jFrameModificar.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Correo a modificar ");
        jFrameModificar.getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 30, 190, 22);
        jFrameModificar.getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 70, 270, 40);

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jFrameModificar.getContentPane().add(jButton8);
        jButton8.setBounds(130, 180, 120, 40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("GENERAR USUARIOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("INSERTAR USUARIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("MODIFICAR USUARIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ELIMINAR USUARIO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbl_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(60, 60, 60)
                        .addComponent(jButton3)
                        .addGap(53, 53, 53)
                        .addComponent(jButton4)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String [] cabecera = {"ID Usuario","Usuario","Contraseña","Nombre","Correo"};
        Object [][] filas = ConexionBD.leerdatosArray("select *from tbl_mostrar");
        DefaultTableModel dtm = new DefaultTableModel(filas,cabecera);
        tbl_mostrar.setModel(dtm);
        tbl_mostrar.setVisible(true);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("USER_ID");
        modelo.addColumn("USERNAME");
        modelo.addColumn("PASSWORD");
        modelo.addColumn("FULLNAME");
        modelo.addColumn("EMAIL");
        tbl_mostrar.setModel(modelo);
        
        
            
        

       
        
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFrameEliminar.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        jFrameUsuario.setVisible(true);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
       
        
        try {
            int nuId = Integer.parseInt(Id_usua.getText());
            String usua = jTextUsuario.getText();
            String contra= jTextContraseña.getText();
            String nom = jTextNombres.getText();
            String corr = jTextCorreo.getText();
           
      
            Recursos nt = new Recursos();
            nt.Insertar(nuId, usua, contra, nom, corr);
             
            LimpiarUsau();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Usuario no ingresado");
        }
        
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       try{ 
        int id= Integer.parseInt(JtxtELiminar.getText());
       Recursos rt = new Recursos();
       rt.Eliminar(id);
       
       
       LimpiarUsau();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Dato no encontrado");
           
       }
              
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jFrameModificar.setVisible(true);
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Id_usuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_usuaActionPerformed
   
    }//GEN-LAST:event_Id_usuaActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafico().setVisible(true);
            }
        });
    }
    
  

    
    
   void LimpiarUsau(){
   Id_usua.setText(null);
   jTextUsuario.setText(null);
   jTextContraseña.setText(null);
   jTextCorreo.setText(null);
   jTextNombres.setText(null);
   JtxtELiminar.setText(null);
   }
   
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_usua;
    private javax.swing.JTextField JtxtELiminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrameEliminar;
    private javax.swing.JFrame jFrameModificar;
    private javax.swing.JFrame jFrameMostar;
    private javax.swing.JFrame jFrameUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextContraseña;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JTable tbl_mostrar;
    // End of variables declaration//GEN-END:variables
}
